development: 
    email: 
      server: your_development_server 
      port: 25 
      domain: your_domain 
      authentication: none 
      username:  
      password:  
      contact_recipient: your_email@server.com 
production: 
    email: 
      server: your_production_server 
      port: 25 
      domain: bphogan.railsplayground.com 
      authentication: login 
      username: username 
      password: your_password 
      contact_recipient: your_email@server.com